In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression, Ridge,Lasso
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.model_selection import RandomizedSearchCV
from catboost import CatBoostRegressor
from xgboost import XGBRegressor
import warnings

In [19]:
df= pd.read_csv('stud.csv')

In [20]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [21]:
x=df.drop(columns=['math score'],axis=1) #creating x & y variable.removing math score and taking rest all as independent variable and from these we predict math score

In [22]:
y=df['math score']

In [23]:
x.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,74
1,female,group C,some college,standard,completed,90,88
2,female,group B,master's degree,standard,none,95,93
3,male,group A,associate's degree,free/reduced,none,57,44
4,male,group C,some college,standard,none,78,75

In [24]:
y.head()

0    72
1    69
2    90
3    47
4    76
Name: math score, dtype: int64

In [25]:
#create column transformer with 3 types of transformers
num_features=x.select_dtypes(exclude='object').columns
cat_features=x.select_dtypes(include='object').columns

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer= StandardScaler()
oh_transformer= OneHotEncoder()

preprocessor=ColumnTransformer(
    [
        ("OneHotEncoder",oh_transformer,cat_features),
         ("StandardScaler",numeric_transformer,num_features),

    ]

  
)

In [26]:
x = preprocessor.fit_transform(x)

In [27]:
x

array([[ 1.        ,  0.        ,  0.        , ...,  1.        ,
         0.19399858,  0.39149181],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         1.42747598,  1.31326868],
       [ 1.        ,  0.        ,  0.        , ...,  1.        ,
         1.77010859,  1.64247471],
       ...,
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         0.12547206, -0.20107904],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         0.60515772,  0.58901542],
       [ 1.        ,  0.        ,  0.        , ...,  1.        ,
         1.15336989,  1.18158627]], shape=(1000, 19))

In [28]:
x.shape

(1000, 19)

In [29]:
#seperate dataset into train & test
from sklearn.model_selection import train_test_split

In [30]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)
x_train.shape, x_test.shape

((800, 19), (200, 19))

In [31]:
#create an evaluate function to give all metrics after model training
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square = r2_score(true,predicted)
    return mae, rmse, r2_square

In [ ]:
models = {
    "Linear Regression": LinearRegression(),
    "Lasso": Lasso(),
    "Ridge": Ridge(),
    "K-Neighbors Regressor": KNeighborsRegressor(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest Regressor": RandomForestRegressor(),
    "XGBRegressor": XGBRegressor(),
    

    "CatBoost Regressor": CatBoostRegressor(verbose=False)
}

model_list = []
r2_list = []

for i in range(len(models)):

    model = list(models.values())[i]

    # Train
    model.fit(x_train, y_train)

    # Predictions
    y_train_pred = model.predict(x_train)
    y_test_pred = model.predict(x_test)

    # Evaluation
    model_train_mae, model_train_rmse, model_train_r2 = evaluate_model(
        y_train, y_train_pred
    )

    model_test_mae, model_test_rmse, model_test_r2 = evaluate_model(
        y_test, y_test_pred
    )

    #print(models.keys().__iter__().__next__())
    print(list(models.keys())[i])

    print("Training Set")
    print("RMSE :", model_train_rmse)
    print("MAE  :", model_train_mae)
    print("R2   :", model_train_r2)

    print("---------------------------")

    print("Test Set")
    print("RMSE :", model_test_rmse)
    print("MAE  :", model_test_mae)
    print("R2   :", model_test_r2)

    model_list.append(list(models.keys())[i])
    r2_list.append(model_test_r2)

    print("=" * 35)

Linear Regression
Linear Regression
Training Set
RMSE : 5.323050852720514
MAE  : 4.266711846071957
R2   : 0.8743172040139593
---------------------------
Test Set
RMSE : 5.393993869732843
MAE  : 4.21476314247485
R2   : 0.8804332983749565
===================================
Linear Regression
Lasso
Training Set
RMSE : 6.593815587795566
MAE  : 5.206302661246526
R2   : 0.8071462015863456
---------------------------
Test Set
RMSE : 6.519694535667419
MAE  : 5.157881810347763
R2   : 0.8253197323627853
===================================
Linear Regression
Ridge
Training Set
RMSE : 5.323324922741654
MAE  : 4.264987823725981
R2   : 0.8743042615212909
---------------------------
Test Set
RMSE : 5.390387016935642
MAE  : 4.211100688014261
R2   : 0.8805931485028737
===================================
Linear Regression
K-Neighbors Regressor
Training Set
RMSE : 5.707683417990174
MAE  : 4.516749999999999
R2   : 0.8554978341651085
---------------------------
Test Set
RMSE : 7.253040741647602
MAE  : 5.621
R2   : 0.7838129945787431
===================================
Linear Regression
Decision Tree
Training Set
RMSE : 0.2795084971874737
MAE  : 0.01875
R2   : 0.9996534669718089
---------------------------
Test Set
RMSE : 7.783315488916019
MAE  : 6.1
R2   : 0.7510462795843155
===================================
Linear Regression
Random Forest Regressor
Training Set
RMSE : 2.277131667297333
MAE  : 1.8181708333333335
R2   : 0.9769998383053788
---------------------------
Test Set
RMSE : 6.0206194065224246
MAE  : 4.627995833333333
R2   : 0.8510393014904576
===================================
Linear Regression
XGBRegressor
Training Set
RMSE : 1.0072816737145132
MAE  : 0.687466561794281
R2   : 0.9954995512962341
---------------------------
Test Set
RMSE : 6.47330716071189
MAE  : 5.057730674743652
R2   : 0.8277965784072876
===================================
Linear Regression
CatBoost Regressor
Training Set
RMSE : 3.042664195326799
MAE  : 2.405393926779502
R2   : 0.9589358676277713
---------------------------
Test Set
RMSE : 6.008631956907363
MAE  : 4.612531714976557
R2   : 0.8516318920747058
===================================

In [39]:
pd.DataFrame(list(zip(model_list, r2_list)), columns=['Model Name', 'R2_Score']).sort_values(by=["R2_Score"],ascending=False)

                Model Name  R2_Score
2                    Ridge  0.880593
0        Linear Regression  0.880433
7       CatBoost Regressor  0.851632
5  Random Forest Regressor  0.851039
6             XGBRegressor  0.827797
1                    Lasso  0.825320
3    K-Neighbors Regressor  0.783813
4            Decision Tree  0.751046